#!/bin/sh

case "$2" in
  template)
    gittemplatefile=$(git config --get commit.template | sed "s|~|$HOME|g");
    cat $gittemplatefile > $1;
    echo "\n#" >> $1;
    git status -sb | head -n 1 | sed 's/^##/#/g' >> $1;
    git diff --cached --stat | sed 's/^/#/g' >> $1;
    echo "#\n#" >> $1;
    git diff --cached | sed 's/^/# /g' >> $1;;
  commit)
    a=$(cat $1 | grep -v "^#");
    echo "$a" > $1;
    gittemplatefile=$(git config --get commit.template | sed "s|~|$HOME|g");
    cat $gittemplatefile >> $1;
    printf "\n#\n# Comitted " >> $1;
    git log --pretty=format:'%cr' -n 1 >> $1;
    echo "" >> $1;
    git diff --cached --stat HEAD^ | sed 's/^/#/g' >> $1;
    echo "#\n#" >> $1;
    git diff --cached HEAD^ | sed 's/^/# /g' >> $1;;
esac
